- name: thursday challange 
  #hosts: bugs,daffy, elmer
  hosts: renamed,!taz
  connection: ssh 
  gather_facts: no
  become: true

  vars:
    username: "carlos"


  tasks:
  - name: Ensure group "funkytown" exists
    ansible.builtin.group:
       name: funkytown
       state: present
     #become: true
  
  - name: "Create user"
    ansible.builtin.user:
            #name: carlos
      name: "{{ username}}"
      group: funkytown
    #become: true
       
